environment:
  matrix:
    - JULIAVERSION: "stable/win64"
    - JULIAVERSION: "download/win64"

branches:
  only:
    - master
 
notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: (new-object net.webclient).DownloadFile($("http://status.julialang.org/"+$env:JULIAVERSION), "C:\projects\julia-binary.exe")
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia

init:
  - git config --global core.autocrlf input

build_script:
  - C:\projects\julia\bin\julia -e "versioninfo()"

test_script:
  - C:\projects\julia\bin\julia --color=yes test/runtests.jl
